name: SPS Frontend CI

on:
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  testing:
    name: Run Flutter testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: "temurin"
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.10.0'
          channel: "stable"
      - run: flutter pub get
      - name: Flutter Analysis
        run: flutter analyze
      - name: Flutter Testing
        run: flutter test
      - name: Code Coverage Report
        run: flutter test --coverage
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3.1.1
        with:
          fail_ci_if_error: true
          file: ./coverage/lcov.info

  build-ios:
    name: Build Flutter App iOS
    needs: [ testing ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: "temurin"
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.10.0'
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter create .
      - run: flutter build ios --no-codesign

  build-android:
    name: Build Android apk bundle
    needs: [ testing ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: "temurin"
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.10.0'
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
